### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MazenDB** [oddmouse/cordova-plugin-locktask#8]
This method seems to be outdated. Do you have any update or a new method I can use

**Comment by janpio** [comment]
You were complaining that your issue here didn't receive an answer via an issue to Cordova itself: https://issues.apache.org/jira/browse/CB-12899

I see pretty obvious reasons:

1. Meaningless title
2. One line accusation with no information what you are talking about, what you tried before, which errors you got etc.

I suggest you use a new issue "How to use this plugin?" where you include exactly what and how you tried to implement it in your project, which error messages you got (or which unexpected behaviour) and what else you did to try to solve it.
